### ISSUE TITLE
Kanal Info

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/Tchatch#10]
Ein fenster in der die Kanal Info angezeigt wird wäre genial. Dann könnte ich über den Chat sehen wie viele Viewer ich aktuell habe, welchen Titel mein kanal trägt usw.

**Comment by PakL** [comment]
Den Titel kann man bereits sehen. Die Viewer-Zahl wollte ich groß daneben auf die rechte Seite packen.
Eine Extra-Funktion zum Ändern von Kanalinfos kommt noch, hat für mich aber keine Priorität.

**Comment by PakL** [comment]
Hinzugefügt in 0a81c3dfce25edee15df797568ecec6f5bebc37e
