### ISSUE TITLE
MAC & PC: Wort Highlights

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/Tchatch#13]
Es gibt ein Problem mit dem WORT Highlights. Wenn man selber seinen Namen schreibt taucht der Name doppelt auf, der erste wird gehighlithed. Schreibt jemand anderes den Namen so wird auch zweimal der Name gezeigt, jedoch wird beim zweiten gehighliteten Wort der erste Buchstabe weggeschnitten.

**Comment by PakL** [comment]
Wird mit dem nächsten Patch behoben.
