### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/Tchatch#21]
Der Modus für das dunkle Designs funktioniert leider nicht mehr.

**Comment by PakL** [comment]
Kinda fixed in [v0.7.3](https://github.com/PakL/Tchatch/releases/tag/v0.7.3), but it's not working for new windows (channel manager) being opend, after the option has been activated...

**Comment by PakL** [comment]
Fixed with commit 39d9eea387ed4184782aa00fca5ad69be793069b (v0.7.4)
