### ISSUE TITLE
Chat-Befehle

### ISSUE THREAD

**Issue by Wolfsterror** [PakL/Tchatch#8]
Die von Twitch mitgelieferten Chat-Befehle werden nicht angezeigt. Aus /me xxxxx eird auch /me xxxxx
das sollte aber so nicht sein.

**Comment by PakL** [comment]
Das musst du mir eventuell besser erklären. Welche Chat-Befehle werden wo nicht angezeigt?
Eine /me-Action sollte ich hinbekommen.

**Comment by PakL** [comment]
/me-Befehle hab ich mit commit 476927e75bb31efe255e7d5600d1418d382cbec8 eingebaut. Wenn da noch was zu kommt, bitte melden.

**Comment by PakL** [comment]
Nehme an, das war alles.

**Comment by Wolfsterror** [comment]
Da kommt noch was zu _pfeif_ http://help.twitch.tv/customer/portal/articles/659095-chat-moderation-commands

**Comment by PakL** [comment]
Geht nun alles im neuen Release [v0.3.0](https://github.com/PakL/Tchatch/releases/tag/v0.3.0)
